[FluffyChat]
preview = "fluffychat.png"
summary = "FluffyChat is a Flutter-based client with a simple and clean UI."
maintainer = "Krille"
platforms = [{name="Android",url=""}, {name="iOS",url=""}, {name="Web",url=""}, {name="Desktop",url=""}]
license = "AGPLv3"
last_release = "2021-12-01"
maturity = "Stable"
source = "https://gitlab.com/famedly/fluffychat"
website = "https://fluffychat.im"
matrix_room = "#fluffychat:matrix.org"
featured = true